WebApplication5/Controllers/ordersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
	public class ordersController : Controller
	{
		private readonly WebApplication5Context _context;

		public ordersController(WebApplication5Context context)
		{
			_context = context;
		}

		// GET: orders
		public async Task<IActionResult> Index()
		{
			return _context.orders != null ?
						View(await _context.orders.ToListAsync()) :
						Problem("Entity set 'WebApplication5Context.orders'  is null.");
		}

		// GET: orders/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null || _context.orders == null)
			{
				return NotFound();
			}

			var orders = await _context.orders
				.FirstOrDefaultAsync(m => m.Id == id);
			if (orders == null)
			{
				return NotFound();
			}

			return View(orders);
		}

		// GET: orders/Create
		public async Task<IActionResult> Create(int? id)
		{
			var book = await _context.book.FindAsync(id);

			return View(book);
		}


		// POST: orders/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(int bookId, int quantity)
		{
			orders order = new orders();
			order.bookId = bookId;
			order.quantity = quantity;

			order.userid = Convert.ToInt32(HttpContext.Session.GetString("userid")); ;
			order.orderdate = DateTime.Today;

			SqlConnection conn = new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\EL10_gazy\\Documents\\mynewdb3.mdf;Integrated Security=True;Connect Timeout=30");
			string sql;
			sql = "UPDATE book  SET bookquantity  = bookquantity   - '" + order.quantity + "'  where (id ='" + order.bookId + "' )";
			SqlCommand comm = new SqlCommand(sql, conn);
			conn.Open();
			comm.ExecuteNonQuery();



			_context.Add(order);
			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(myorders));


		}


		public async Task<IActionResult> myorders()
		{

			int id = Convert.ToInt32(HttpContext.Session.GetString("userid")); ;
			var orItems = await _context.orders.FromSqlRaw("select *  from orders where  userid = '" + id + "'  ").ToListAsync();
			return View(orItems);

		}

		public async Task<IActionResult> customerOrders(int? id)
		{


			var orItems = await _context.orders.FromSqlRaw("select *  from orders where  userid = '" + id + "'  ").ToListAsync();
			return View(orItems);

		}

		public async Task<IActionResult> customerreport()
		{
			var orItems = await _context.report.FromSqlRaw("select usersaccounts.id as Id, name as customername, sum (quantity * Price)  as total from book, orders,usersaccounts  where usersaccounts.id = orders.userid  and bookid= book.Id group by name,usersaccounts.id ").ToListAsync();
			return View(orItems);

		}


		// GET: orders/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null || _context.orders == null)
			{
				return NotFound();
			}

			var orders = await _context.orders.FindAsync(id);
			if (orders == null)
			{
				return NotFound();
			}
			return View(orders);
		}

		// POST: orders/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,bookId,userid,quantity,orderdate")] orders orders)
		{
			if (id != orders.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(orders);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ordersExists(orders.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(orders);
		}

		// GET: orders/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null || _context.orders == null)
			{
				return NotFound();
			}

			var orders = await _context.orders
				.FirstOrDefaultAsync(m => m.Id == id);
			if (orders == null)
			{
				return NotFound();
			}

			return View(orders);
		}

		// POST: orders/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (_context.orders == null)
			{
				return Problem("Entity set 'WebApplication5Context.orders'  is null.");
			}
			var orders = await _context.orders.FindAsync(id);
			if (orders != null)
			{
				_context.orders.Remove(orders);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool ordersExists(int id)
		{
			return (_context.orders?.Any(e => e.Id == id)).GetValueOrDefault();
		}

		[HttpPost]
        public IActionResult AddToCart(int bookId, int quantity)
        {
            // Get the cart from the session.
            Cart cart = HttpContext.Session.GetObject<Cart>("cart");

            // If the cart doesn't exist, create a new one.
            if (cart == null)
            {
                cart = new Cart();
                HttpContext.Session.SetObject("cart", cart);
            }

            // Find the book in the database.
            book book = _context.book.FirstOrDefault(b => b.Id == bookId);

            if (book != null)
            {
                // Add the item to the cart.
                CartItem cartItem = new CartItem
                {
                    Book = book,
                    Quantity = quantity
                };

                cart.Items.Add(cartItem);

                // Update the total amount of the cart.
                cart.Total += cartItem.Book.price * cartItem.Quantity;

                // Update the cart in the session.
                HttpContext.Session.SetObject("cart", cart);
            }

            // Redirect to the cart view.
            return RedirectToAction("Cart");
        }


        public IActionResult Cart()
		{
			// Get the cart from the session.
			Cart cart = HttpContext.Session.GetObject<Cart>("cart");

			// If the cart doesn't exist, create a new one.
			if (cart == null)
			{
				cart = new Cart();
				HttpContext.Session.SetObject("cart", cart);
			}

			// Return the cart view.
			return View(cart);
		}
	}
}

WebApplication5/Controllers/usersaccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class usersaccountsController : Controller
    {
        private readonly WebApplication5Context _context;

        public usersaccountsController(WebApplication5Context context)
        {
            _context = context;
        }

        // GET: usersaccounts
        public async Task<IActionResult> Index()
        {
              return _context.usersaccounts != null ? 
                          View(await _context.usersaccounts.ToListAsync()) :
                          Problem("Entity set 'WebApplication5Context.usersaccounts'  is null.");
        }

        // GET: usersaccounts/Details/5


        // GET: usersaccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        public IActionResult login()
        {
            return View();
        }

        [HttpPost, ActionName("login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> login(string na, string pa)
        {
            SqlConnection conn1 = new SqlConnection("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\EL10_gazy\\Documents\\mynewdb3.mdf;Integrated Security=True;Connect Timeout=30");
            string sql;
            sql = "SELECT * FROM usersaccounts where name ='" + na + "' and  pass ='" + pa + "' ";
            SqlCommand comm = new SqlCommand(sql, conn1);
            conn1.Open();
            SqlDataReader reader = comm.ExecuteReader();

            if (reader.Read())
            {
                string role = (string)reader["role"];
                string id = Convert.ToString((int)reader["Id"]);
                HttpContext.Session.SetString("Name", na);
                HttpContext.Session.SetString("Role", role);
                HttpContext.Session.SetString("userid", id);
                reader.Close();
                conn1.Close();
                if (role == "customer")
                    return RedirectToAction("catalogue", "books");

                else
                    return RedirectToAction("Index", "books");

            }
            else
            {
                ViewData["Message"] = "wrong user name password";
                return View();
            }
        }

        // POST: usersaccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,pass,email")] usersaccounts usersaccounts)
        {
            usersaccounts.role = "customer";


                _context.Add(usersaccounts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(login));
           
        }

        // GET: usersaccounts/Edit/5
        public async Task<IActionResult> Edit()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("userid"));


            var usersaccounts = await _context.usersaccounts.FindAsync(id);

            return View(usersaccounts);
        }

        // POST: usersaccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,name,pass,role,email")] usersaccounts usersaccounts)
        {

                    _context.Update(usersaccounts);
                    await _context.SaveChangesAsync();
               
                return RedirectToAction(nameof(login));

        }



        private bool usersaccountsExists(int id)
        {
          return (_context.usersaccounts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="site-logo">
                    <a style="
			padding-left: 0;
			font-size: 30px;
			font-weight: bold;
			">eBook</a>
                    <a style="
			padding-left: 0;
			font-size: 30px;
			padding-right: 50px;
			font-weight: bold;
			color: #33cabb;" class="navbar-brand" href="#">Store</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Create">Add Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Manage Books</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="orders" asp-action="customerreport">Order reports</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="usersaccounts" asp-action="Index">Cutomers List</a>
                            </li>
                        </ul>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication5/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="site-logo">
                    <a style="padding-left: 0; font-size: 30px; font-weight: bold;">eBook</a>
                    <a style="padding-left: 0; font-size: 30px; padding-right: 50px; font-weight: bold; color: #33cabb;" class="navbar-brand" href="#">Store</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="catalogue">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="orders" asp-action="myorders">My Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="usersaccounts" asp-action="Edit">Profile</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a style="color: white;" asp-area="" asp-controller="orders" asp-action="Cart">
                                Cart <img src="~/images/shopping-cart2.png" alt="Cart" style="vertical-align: auto; height: 30px;">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eBookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>